// Testbench for systolic array top.
// Reads hex files generated by scripts/gen_test_data.py, loads them into the DUT,
// runs the accelerator, and compares memO output to golden_O.hex.
//
// Run from project root:
//   1. python3 scripts/gen_test_data.py   (generates tb/data/*.hex)
//   2. Compile rtl/*.sv and this tb/tb_top.sv, run simulation.
//   File paths are relative to the simulator's cwd (e.g. tb/data/memA.hex).

module tb_top;

    localparam int N        = 4;
    localparam int DATA_W   = 16;
    localparam int INSTR_W  = 16;
    localparam int DEPTH_A  = 2048;
    localparam int DEPTH_B  = 2048;
    localparam int DEPTH_O  = 2048;
    localparam int DEPTH_I  = 64;
    localparam int N_SQ     = N * N;

    logic        clk;
    logic        rst_n;
    logic        ap_start;
    logic        ap_done;

    logic [10:0] addrA;
    logic        enA;
    logic [15:0] dataA;

    logic [10:0] addrB;
    logic        enB;
    logic [15:0] dataB;

    logic [5:0]  addrI;
    logic        enI;
    logic [15:0] dataI;

    logic [10:0] addrO;
    logic [15:0] dataO;

    // -------------------------------------------------------------------------
    // Clock and reset
    // -------------------------------------------------------------------------
    initial clk = 0;
    always #5 clk = ~clk;

    initial begin
        rst_n = 0;
        repeat (3) @(posedge clk);
        rst_n = 1;
    end

    // -------------------------------------------------------------------------
    // Load hex files generated by Python (paths relative to simulator cwd)
    // -------------------------------------------------------------------------
    logic [15:0] memA_file [0:DEPTH_A-1];
    logic [15:0] memB_file [0:DEPTH_B-1];
    logic [15:0] memI_file [0:DEPTH_I-1];
    logic [15:0] golden_O  [0:DEPTH_O-1];

    initial begin
        $readmemh("tb/data/memA.hex",    memA_file);
        $readmemh("tb/data/memB.hex",   memB_file);
        $readmemh("tb/data/memI.hex",   memI_file);
        $readmemh("tb/data/golden_O.hex", golden_O);
    end

    // -------------------------------------------------------------------------
    // DUT
    // -------------------------------------------------------------------------
    top #(
        .N       (N),
        .DATA_W  (DATA_W),
        .ACC_W   (32),
        .INSTR_W (INSTR_W),
        .DEPTH_A (DEPTH_A),
        .DEPTH_B (DEPTH_B),
        .DEPTH_O (DEPTH_O),
        .DEPTH_I (DEPTH_I)
    ) u_dut (
        .clk     (clk),
        .rst_n   (rst_n),
        .ap_start(ap_start),
        .ap_done (ap_done),
        .addrA   (addrA),
        .enA     (enA),
        .dataA   (dataA),
        .addrB   (addrB),
        .enB     (enB),
        .dataB   (dataB),
        .addrI   (addrI),
        .enI     (enI),
        .dataI   (dataI),
        .addrO   (addrO),
        .dataO   (dataO)
    );

    // -------------------------------------------------------------------------
    // Test sequence: load A, B, I -> ap_start -> wait ap_done -> read O -> compare
    // -------------------------------------------------------------------------
    int load_addr;
    int err_count;

    initial begin
        ap_start = 0;
        enA = 0; enB = 0; enI = 0;
        addrA = '0; addrB = '0; addrI = '0; addrO = '0;
        dataA = '0; dataB = '0; dataI = '0;
        err_count = 0;

        @(posedge rst_n);
        repeat (2) @(posedge clk);

        // ----- Load matrix A (row-major, N*N words) -----
        for (load_addr = 0; load_addr < N_SQ; load_addr++) begin
            @(posedge clk);
            addrA = load_addr;
            dataA = memA_file[load_addr];
            enA   = 1;
        end
        @(posedge clk); enA = 0;

        // ----- Load matrix B (column-major in file, N*N words) -----
        for (load_addr = 0; load_addr < N_SQ; load_addr++) begin
            @(posedge clk);
            addrB = load_addr;
            dataB = memB_file[load_addr];
            enB   = 1;
        end
        @(posedge clk); enB = 0;

        // ----- Load instruction memory (a, b, c, 0) -----
        for (load_addr = 0; load_addr < DEPTH_I; load_addr++) begin
            @(posedge clk);
            addrI = load_addr;
            dataI = memI_file[load_addr];
            enI   = 1;
            if (memI_file[load_addr] == 0) break;  // stop after terminator
        end
        @(posedge clk); enI = 0;

        repeat (2) @(posedge clk);

        // ----- Start accelerator -----
        @(posedge clk);
        ap_start = 1;
        @(posedge clk);
        ap_start = 0;

        // ----- Wait for completion -----
        wait (ap_done);
        $display("[TB] ap_done asserted.");
        repeat (2) @(posedge clk);

        // ----- Read O and compare to golden (sync read: set addrO, next cycle dataO is valid) -----
        for (int i = 0; i < N_SQ; i++) begin
            @(posedge clk);
            addrO = i;
            @(posedge clk);
            if (dataO !== golden_O[i]) begin
                $display("[TB] MISMATCH at O[%0d]: got %04X, golden %04X", i, dataO, golden_O[i]);
                err_count++;
            end
        end

        // ----- Report -----
        repeat (2) @(posedge clk);
        if (err_count == 0)
            $display("[TB] PASS: All %0d outputs match golden.", N_SQ);
        else
            $display("[TB] FAIL: %0d mismatches.", err_count);
        $finish;
    end

endmodule
